name: Test Startup

on:
  pull_request:
    branches: [main, develop]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install backend dependencies
        run: |
          cd backend
          npm cache clean --force
          rm -f package-lock.json
          npm install

      - name: Test backend startup
        run: |
          cd backend
          timeout 10s npm start || true
        env:
          MONGO_URI: "mongodb://localhost:27017/test"

  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
           node-version: 22
           cache: "npm"

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm cache clean --force
          rm -f package-lock.json
          npm install

      - name: Test frontend build
        run: |
          cd frontend
          npm run build

      - name: Test frontend dev server startup
        run: |
          cd frontend
          timeout 10s npm run dev || true
